[theme]
name = "nord-dark"

[icons]
name = "none"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"
[block.theme_overrides]
idle_fg = "#eceff4"
idle_bg = "#5e81ac"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "time"
format = "%a %Y-%m-%d %I:%M:%S %p"
timezone = "US/Central"
interval = 1
locale = "en_US"
